### ISSUE TITLE
How to preload with webpack?

### ISSUE THREAD

**Issue by darklightblue** [andreupifarre/preload#7]
```
import Preload from 'preload-it';
import myImage from 'myimagepath.png'

const preload = Preload();
preload
  .fetch([
    myImage,
  ])
  .then((items) => {
    console.log(items);
  });
```

Seems to be not working and will throw an error. :(

**Comment by andreupifarre** [comment]
**preload-it** accepts [Data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs), so with webpack you can use the `url-loader` loader to transform files into base64 URIs, which then can be passed to `fetch`:

for instance this will work fine:     
`preload.fetch(['data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==']);`

so your code above will work fine as it is, you'd just need to update your **webpack.config.js** to use `url-loader` instead of `file-loader` (if that is what you are using). 
something along these lines: `{ test: /\.png$/, loader: "url-loader?mimetype=image/png" }`
